
// 店铺管理

export default [{
  path: '/shop',
  name: '店铺管理',
  icon: 'shop',
  access: 'SHOP',
  routes: [
    {
      path: '/shop/renovation',
      name: '页面装修',
      component: './shop/renovation/list',
      access: 'SHOP_RENOVATION',
    },
    {
      path: '/shop/renovation/new',
      name: '新建页面',
      component: './shop/renovation/new',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_RENOVATIONNEW',
    },
    {
      path: '/shop/renovation/:id/add',
      name: '新增页面',
      component: './shop/renovation/edit',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_RENOVATIONADD',
    },
    {
      path: '/shop/renovation/:id/edit',
      name: '编辑页面',
      component: './shop/renovation/edit',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_RENOVATIONEDIT',
    },
    // {
    //   path: '/shop/renovation/a',
    //   name: '编辑页面',
    //   component: './shop/renovation/a',
    //   hideInMenu: true,
    //   exact: true,
    // },
    {
      path: '/shop/new',
      name: '新增店铺',
      component: './shop/new',
      access: 'SHOP_NEW',
    },
    {
      path: '/shop/classify',
      name: '店铺分类',
      component: './shop/classify',
      access: 'SHOP_CLASSIFY',
    },
    {
      path: '/shop/aftermarket',
      name: '售后说明模版',
      component: './shop/aftermarket',
      access: 'SHOP_AFTERMARKET',
    },
    {
      path: '/shop/aftermarket/add',
      name: '添加售后模版',
      component: './shop/aftermarket/edit',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_AFTERMARKETNEW',
    },
    {
      path: '/shop/aftermarket/:id/edit',
      name: '编辑售后模版',
      component: './shop/aftermarket/edit',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_AFTERMARKETEDIT',
    },
    {
      path: '/shop/topic',
      name: '专题管理',
      component: './shop/topic',
      access: 'SHOP_TOPIC',
    },
    {
      path: '/shop/topic/add',
      name: '添加专题',
      component: './shop/topic/edit',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_TOPICNEW',
    },
    {
      path: '/shop/topic/:id/edit',
      name: '编辑专题',
      component: './shop/topic/edit',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_TOPICEDIT',
    },
    {
      path: '/shop/adsense',
      name: '广告管理',
      component: './shop/adsense',
      access: 'SHOP_ADSENSE',
    },
    {
      path: '/shop/adsense/:id',
      name: '广告管理',
      component: './shop/adsense/detail',
      hideInMenu: true,
      exact: true,
      access: 'SHOP_ADSENSEDETAIL',
    },
    {
      component: './404',
    },
  ],
}]
